spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/floodshield
spring.datasource.username=postgres
spring.datasource.password=23251a1229

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8081